[[redirects]]
 from = "/api/data"
 to = "/.netlify/functions/data"
 status = 200

[[redirects]]
 from = "/api/versions"
 to = "/.netlify/functions/versions"
 status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
